Repository Kushal-Pareek/CodeRed, pull requests merged in 2022-10, with the labels that each got.

#53 added a new folder of spotify clone
  spotify clone/bg.jpg
  spotify clone/covers/1.jpg
  spotify clone/covers/10.jpg
  spotify clone/covers/2.jpg
  spotify clone/covers/3.jpg
  spotify clone/covers/4.jpg
  spotify clone/covers/5.jpg
  spotify clone/covers/6.jpg
  spotify clone/covers/7.jpg
  spotify clone/covers/8.jpg
  spotify clone/covers/9.jpg
  spotify clone/covers/example2
  spotify clone/example
  spotify clone/index.html
  spotify clone/logo.png
  spotify clone/playing.gif
  spotify clone/script.js
  spotify clone/style.css
Labels: Hacktoberfest-accepted

#58 Balloon Shooter Game using Python
  .gitignore
  HACKTOBERFEST-BALLOONSHOOTER-main/.gitignore
  HACKTOBERFEST-BALLOONSHOOTER-main/README.md
  HACKTOBERFEST-BALLOONSHOOTER-main/balloonshooter.iml
  HACKTOBERFEST-BALLOONSHOOTER-main/inspectionProfiles/profiles_settings.xml
  HACKTOBERFEST-BALLOONSHOOTER-main/main.py
  HACKTOBERFEST-BALLOONSHOOTER-main/misc.xml
  HACKTOBERFEST-BALLOONSHOOTER-main/modules.xml
  HACKTOBERFEST-BALLOONSHOOTER-main/workspace.xml
  Online College Election System/css/election.css
  Online College Election System/css/form.css
  Online College Election System/css/home.css
  Online College Election System/html/About.html
  Online College Election System/html/Adminlogin.html
  Online College Election System/html/Campus.html
  Online College Election System/html/Contactus.html
  Online College Election System/html/Departments.html
  Online College Election System/html/Election.html
  Online College Election System/html/Studentregistrationform.html
  Online College Election System/html/home.html
  Online College Election System/html/studentlogin.html
  Online College Election System/html/votedsuccessfully .html
  Online College Election System/image/Rajinikanth.jpg
  Online College Election System/image/ajith.jpg
  Online College Election System/image/atharvaa.jpg
  Online College Election System/image/auditorium.jfif
  Online College Election System/image/bus.png
  Online College Election System/image/canteen1.jpg
  Online College Election System/image/capgemini.jpg
  Online College Election System/image/civil lab.jpg
  Online College Election System/image/clg campus.jpg
  Online College Election System/image/clg student.jpg
  Online College Election System/image/college campus.jpg
  Online College Election System/image/college logo.jpg
  Online College Election System/image/computer.jpg
  Online College Election System/image/cse lab.jpg
  Online College Election System/image/cse.jpg
  Online College Election System/image/ece lab.jpg
  Online College Election System/image/eeee lab.jpg
  Online College Election System/image/food.jpg
  Online College Election System/image/harish.jpg
  Online College Election System/image/hcl.jpg
  Online College Election System/image/hostel.jfif
  Online College Election System/image/jyothika.jpg
  Online College Election System/image/kamal.jfif
  Online College Election System/image/keerthi.jfif
  Online College Election System/image/library 2.jpg
  Online College Election System/image/library.jpg
  Online College Election System/image/mech lab.jpg
  Online College Election System/image/prakash raj.jpg
  Online College Election System/image/sports.jpg
  Online College Election System/image/suriya.jfif
  Online College Election System/image/tcs.png
  Online College Election System/image/vijay.jpg
  Online College Election System/image/wipro.jpg
  Online College Election System/image/zoho.jpg
  Online College Election System/javascript/adminlogin.js
  Online College Election System/javascript/studentlogin.js
  Online College Election System/javascript/studentregistrationform.js
  README.md
Labels: Hacktoberfest-accepted

#61 Guess the no. game using javascript
  GuessTheNumber.js
Labels: Hacktoberfest-accepted

#60 Handling Records of student using dictionary
  records_dictionary.py
Labels: Hacktoberfest-accepted

#64 Create passwordvalidation.py
  passwordvalidation.py
Labels: Hacktoberfest-accepted

#59 TODO List
  TODO List
Labels: Hacktoberfest-accepted, Hacktoberfest

#63 Create library_managment.py
  library_managment.py
Labels: Hacktoberfest-accepted, Hacktoberfest

#71 tic tac games
  Tic Tac Games HTML/function.js
  Tic Tac Games HTML/index
  Tic Tac Games HTML/scss.css
Labels: Hacktoberfest-accepted, Hacktoberfest

#74 add a form to save user details to localstorage
  SurveyForm/README.md
  SurveyForm/Screenshot (61).png
  SurveyForm/index.html
  SurveyForm/main.js
Labels: Hacktoberfest-accepted, Hacktoberfest

#73 Added Tip Calculator Kush
  tip-calculator/Tip calculaor/ReadMe.md
  tip-calculator/Tip calculaor/app.js
  tip-calculator/Tip calculaor/img11.jpg
  tip-calculator/Tip calculaor/index.html
  tip-calculator/Tip calculaor/style.css
Labels: Hacktoberfest-accepted, Hacktoberfest

#81 Text Editor Application
  Text Editor application/.gitignore
  Text Editor application/README.md
  Text Editor application/package-lock.json
  Text Editor application/package.json
  Text Editor application/public/apple-icon-57x57.png
  Text Editor application/public/apple-icon-60x60.png
  Text Editor application/public/apple-icon.png
  Text Editor application/public/favicon.ico
  Text Editor application/public/index.html
  Text Editor application/public/logo192.png
  Text Editor application/public/logo512.png
  Text Editor application/public/manifest.json
  Text Editor application/public/robots.txt
  Text Editor application/src/App.css
  Text Editor application/src/App.js
  Text Editor application/src/App.test.js
  Text Editor application/src/components/About.js
  Text Editor application/src/components/Alert.js
  Text Editor application/src/components/Navbar.js
  Text Editor application/src/components/TextForm.js
  Text Editor application/src/index.css
  Text Editor application/src/index.js
  Text Editor application/src/logo.svg
  Text Editor application/src/reportWebVitals.js
  Text Editor application/src/setupTests.js
Labels: Hacktoberfest-accepted, Hacktoberfest

#82 Create sudoku solver html+Js code
  sudoku solver html+Js code
Labels: Hacktoberfest-accepted, Hacktoberfest

#80 Bill generation project using Java
  Department Store Bill generation Project/build.xml
  Department Store Bill generation Project/build/built-jar.properties
  Department Store Bill generation Project/build/classes/ta/pkg2/BillCalc.class
  Department Store Bill generation Project/build/classes/ta/pkg2/TA2.class
  Department Store Bill generation Project/build/classes/ta/pkg2/customers.txt
  Department Store Bill generation Project/build/classes/ta/pkg2/kirana.txt
  Department Store Bill generation Project/dist/README.TXT
  Department Store Bill generation Project/dist/TA-2.jar
  Department Store Bill generation Project/manifest.mf
  Department Store Bill generation Project/nbproject/build-impl.xml
  Department Store Bill generation Project/nbproject/genfiles.properties
  Department Store Bill generation Project/nbproject/private/config.properties
  Department Store Bill generation Project/nbproject/private/private.properties
  Department Store Bill generation Project/nbproject/private/private.xml
  Department Store Bill generation Project/nbproject/project.properties
  Department Store Bill generation Project/nbproject/project.xml
  Department Store Bill generation Project/src/ta/pkg2/BillCalc.java
  Department Store Bill generation Project/src/ta/pkg2/TA2.java
  Department Store Bill generation Project/src/ta/pkg2/customers.txt
  Department Store Bill generation Project/src/ta/pkg2/kirana.txt
Labels: Hacktoberfest-accepted, Hacktoberfest

#79 Add Martial Arts Simulator Game
  Martial-Arts-Game/README.md
  Martial-Arts-Game/Screenshot (62).png
  Martial-Arts-Game/favicon.png
  Martial-Arts-Game/game.js
  Martial-Arts-Game/images/.DS_Store
  Martial-Arts-Game/images/background.jpg
  Martial-Arts-Game/images/backward/1.png
  Martial-Arts-Game/images/backward/2.png
  Martial-Arts-Game/images/backward/3.png
  Martial-Arts-Game/images/backward/4.png
  Martial-Arts-Game/images/backward/5.png
  Martial-Arts-Game/images/backward/6.png
  Martial-Arts-Game/images/block/1.png
  Martial-Arts-Game/images/block/2.png
  Martial-Arts-Game/images/block/3.png
  Martial-Arts-Game/images/block/4.png
  Martial-Arts-Game/images/block/5.png
  Martial-Arts-Game/images/block/6.png
  Martial-Arts-Game/images/block/7.png
  Martial-Arts-Game/images/block/8.png
  Martial-Arts-Game/images/block/9.png
  Martial-Arts-Game/images/forward/1.png
  Martial-Arts-Game/images/forward/2.png
  Martial-Arts-Game/images/forward/3.png
  Martial-Arts-Game/images/forward/4.png
  Martial-Arts-Game/images/forward/5.png
  Martial-Arts-Game/images/forward/6.png
  Martial-Arts-Game/images/gameimage.png
  Martial-Arts-Game/images/idle/1.png
  Martial-Arts-Game/images/idle/2.png
  Martial-Arts-Game/images/idle/3.png
  Martial-Arts-Game/images/idle/4.png
  Martial-Arts-Game/images/idle/5.png
  Martial-Arts-Game/images/idle/6.png
  Martial-Arts-Game/images/idle/7.png
  Martial-Arts-Game/images/idle/8.png
  Martial-Arts-Game/images/kick/1.png
  Martial-Arts-Game/images/kick/2.png
  Martial-Arts-Game/images/kick/3.png
  Martial-Arts-Game/images/kick/4.png
  Martial-Arts-Game/images/kick/5.png
  Martial-Arts-Game/images/kick/6.png
  Martial-Arts-Game/images/kick/7.png
  Martial-Arts-Game/images/kung-fu.png
  Martial-Arts-Game/images/punch/1.png
  Martial-Arts-Game/images/punch/2.png
  Martial-Arts-Game/images/punch/3.png
  Martial-Arts-Game/images/punch/4.png
  Martial-Arts-Game/images/punch/5.png
  Martial-Arts-Game/images/punch/6.png
  Martial-Arts-Game/images/punch/7.png
  Martial-Arts-Game/index.html
  Martial-Arts-Game/sounds/block.mp3
  Martial-Arts-Game/sounds/canon-strike.mp3
  Martial-Arts-Game/sounds/kick.mp3
  Martial-Arts-Game/sounds/move.mp3
  Martial-Arts-Game/sounds/punch.mp3
  Martial-Arts-Game/sounds/theme.mp3
  Martial-Arts-Game/style.css
Labels: Hacktoberfest-accepted, Hacktoberfest

#83 added and edited dice project
  Dice-Project/images/dice1.png
  Dice-Project/images/dice2.png
  Dice-Project/images/dice3.png
  Dice-Project/images/dice4.png
  Dice-Project/images/dice5.png
  Dice-Project/images/dice6.png
  Dice-Project/index.html
  Dice-Project/index.js
  Dice-Project/styles.css
Labels: good first issue, Hacktoberfest-accepted, Hacktoberfest

#66 Create Snake_game_legends app
  Snake_game_legends.py
Labels: Hacktoberfest-accepted, Hacktoberfest

#86 Added validator project
  cc_validator.cpp
  cc_validator.exe
Labels: Hacktoberfest-accepted, Hacktoberfest

#89 Create creaing_digital_clk.js
  creaing_digital_clk.js
Labels: Hacktoberfest-accepted, Hacktoberfest

#88 Theme
  Theme.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#87 added and updated the weather project using javascript
  WeatherProject/app.js
  WeatherProject/index.html
  WeatherProject/package-lock.json
  WeatherProject/package.json
Labels: Hacktoberfest-accepted, Hacktoberfest
